### ISSUE TITLE
AutoRank Issue "Rank Change of the Rank 'Honoured' is Invalid"

### ISSUE THREAD

**Issue by OlleyGibson** [Staartvin/Autorank-2#166]
Please can i have some help with this? I have tried alot of things to fix it and i cannot see any errors in the Advance Config so i have no idea what could be wrong with it?
Here is some of the important Config, please have a look :)

```
Citizen:
    requirements:
        time:
            value: 16h
        exp:
            value: 20
    results:
        rank change: Citizen;honoured
        command: 'say &p has just been promoted to Honoured!; give &p 264 16; tell &p You have just earned 16 Diamonds!'
        message: 'Congratulations, you are now a Honoured.'
Honoured:
    requirements:
        time:
            value: 48h
        exp:
            value: 45
    results:
        rank change: honoured;Legend
        command: 'say &p has just been promoted to Legend!; give &p 264 32; tell &p You have just earned 32 Diamonds!'
        message: 'Congratulations, you are now a Legend.'
```

Thanks,
Olley Gibson
