### ISSUE TITLE
Error when you don't set the block data type

### ISSUE THREAD

**Issue by FrozenBeard** [Staartvin/Autorank-2#440]
Ahoy!
Took me a while to figure out why I was getting internal errors;
When you use blocks broken, and you don't set a data parameter then youll get an internal error, It was either one of these, I cant remember, I think it was block 17.
`   blocks broken: 56;5;0
    blocks broken2: 17;700;0
`
If you leave the 0 of one of those you'll get an internal server error when you do an /ar check
You should default to 0 if none is put in.

**Comment by Staartvin** [comment]
Hmm, strange; I don't seem to get that error. I used this config:

```YAML
Test:
  prerequisites:
    world: world_nether
    money: 1000
    blocks broken: 56;100
  requirements:
    money: 10000
    blocks broken: 50
  results:
    rank change: TestGroup2
    command: broadcast &p has just completed path 'Default'!
    command2: give &p 1 100
    message: Congratulations, you completed the 'Default' path!
  options:
    display name: Test path
```

**Worked fine for me.** Maybe something else was incorrectly formatted?
