### ISSUE TITLE
Autorank 4 not auto ranking players

### ISSUE THREAD

**Issue by frizzbee30** [Staartvin/Autorank-2#444]
Hi, I wonder if you can help. We currently use 3.8 with no issues in live, but I'm eagerly testing 4 on our test server. We currently have the below advanced config running great in live. After 10 hours on the server players automatically rank up to explorer in our survival maps only (we run multiverse)

```YAML
ranks:
    Traveler:
     requirements:
          time:
              value: 10h
     results:
          rank change: Traveler;Explorer;Survival Map
          command: 'pex user &p group set Explorer "Survival Map_the_end"'
          message: 'Congratulations, you are now an Explorer.'
```

However, when transferring to paths in version 4, there is no 'auto rankup' and the plugin demands that a path be chosen by name? There is currently only 1 path, plus we would always want players to follow this path, then if we add more , there would be a choice.

 We are aiming to give secondary titles to players according to play time and world (which adavanced.yml will do), but I'm a bit wary that version 4 won't do the same after testing.

paths config

```YAML
Travelertoexplorer:
  prerequisites:
    in group:
      value: Traveler
  requirements:
    time:
      value: 10h
  results:
    rank change: Traveler;Explorer;Survival Map
    command:
      value: pex user &p group set Explorer "Survival Map_the_end"
    message:
      value: Congratulations, you are now an Explorer.
  options:
    infinite pathing: true
```

Could you advise? I have also tried adding the auto complete option too, with no success.

The infinite pathing has been added to replace the removal of infinite ranking from settings.yml :)
