### ISSUE TITLE
Autorank 4: New Paths.yml 

### ISSUE THREAD

**Issue by nathan93** [Staartvin/Autorank-2#445]
I am not a fan of this update that replaces the AdvancedConfig with this new Paths.yml, but I guess I'll have to live with it. 

The wiki isn't giving an explanation for what I need. I simply want players to be ranked up if they meet certain requirements, none of this other extra complicated stuff. My AdvancedConfig on Autorank 3.8 looked like this http://pastebin.com/thtVjFTJ

All I want is simply for that to work. How might I do that with this new update?

**Comment by Staartvin** [comment]
I'm sorry that you're having troubles with the new format. I tried to keep the format close to what Autorank originally had. The good news is that Paths.yml and the AdvancedConfig share more or less the same format. The biggest change you'll have to perform is that each path will have a prerequisite that is the 'in group'. 

Take a look at your Member group. You would create a new path, for example Member to Novice, that has a prerequisite 'in group' with value 'Member'. The requirements and results sections can be copied from the AdvancedConfig.  

That's it!

**Comment by nathan93** [comment]
Do you have an example of what the configuration of Paths.yml might look like for Member to Novice? I understand that you need a prerequisite, however what I'm not understanding is how to format it in the configuration.

**Comment by Staartvin** [comment]
Here's an example for the Member to Novice group:

```YAML

Member to Novice:
    prerequisites:
        in group:
            value: Member
    requirements:
        mcmmo power level:
            value: 100
        time:
            value: 2h
    results:
        rank change: Novice
        command: 'bc &p has just been promoted to &bNovice&a, and earned &91 crate key!; crate givekey &p SionCrate 1; tell &p You have just earned 1 crate key!'
        message: 'Congratulations, you are now a Novice!'
```

There you go! Looks a lot like the AdvancedConfig.yml!
