### ISSUE TITLE
Options won't "load"

### ISSUE THREAD

**Issue by zerafox** [Staartvin/Autorank-2#462]
Having trouble getting the file to accept the 'options'. I've altered all kinds of indentation and what-not but it just doesn't work.
Leaving it out player's weren't being Ranked at all, so I was forced to make some alterations.
```
Default:
  prerequisites:
    permission:
      value: rank.1
  requirements:
    time: 12h
      options:
        auto complete: true
  results:
    command: lp user &p promote player
    message: Congratulations, you were promoted to Novice!
  options:
    display name: Novice Rank
    auto choose: true
    show based on prerequisites: true
```

**Comment by Staartvin** [comment]
It seems like this is a valid path, but the Yaml is invalid. I ran it through a yaml parser and found this is correct:

```YAML
Default:
  prerequisites:
    permission:
      value: rank.1
  requirements:
    time:
      value: 12h
      options:
        auto complete: true
  results:
    command: lp user &p promote player
    message: Congratulations, you were promoted to Novice!
  options:
    display name: Novice Rank
    auto choose: true
    show based on prerequisites: true
```
