### ISSUE TITLE
Auto Rank Setup

### ISSUE THREAD

**Issue by MobBootyHunter** [Staartvin/Autorank-2#537]
Im new to the autorank plugin, and i honestly can not understand how to do a thing. The tutorials are confusing and i dont explain how rank pathing works. I just want to create a simple ranking path that contains 5-6 ranks. Can someone help explain how i can do this?

**Comment by Staartvin** [comment]
If you want to create a path from Rank A to Rank B, you can have three properties:
1. Prerequisites
2. Requirements
3. Results

The prerequisites specify what conditions must be met for a player to 'join' the path.
The requirements are the conditions that a player needs to meet for it to complete the path, once the player has actually joined the path.
Lastly, when the player has met all requirements, the results are performed to give the player some rewards, or to trigger some stuff.

Now, here's an example of a path: 

```YAML
Running a marathon:
    prerequisites:
        in group: 
            value: Participants
        money: 
            value: 100
    upon choosing:
        command: 
            value: "eco take &p 100"
        message: 
            value: "You are now participating in a marathon!"
    requirements:
        blocks moved: 
            value: 1000;0
    results:
        money: 
            value: 10000
```

This path will award players with money (see the results property), once they meet the requirement 'blocks moved'. Note that in order for the player to 'start' this path, he needs to be in the permissions group 'Participants' and have 100 money. The upon choosing property can be used to perform results when a player 'starts' the path. See [this page](https://github.com/Staartvin/Autorank-2/wiki/How-to-configure-the-Paths.yml-file%3F) for more details.

Is that clear to you?
