### ISSUE TITLE
Using AdvancedConfig.yml, not ranking up

### ISSUE THREAD

**Issue by Prxmium** [Staartvin/Autorank-2#541]
I'm helping my friend set up the AdvancedConfig.yml, and from what I can determine, I've set it up properly, but we aren't being ranked up after meeting the time requirement, which is the only requirement.

Here is the config file: https://hastebin.com/obupodajes.coffeescript

**Comment by BolsaFamiliaBR** [comment]
I think the problem is here.
**rank change: Apprentice**

You need put 
rank change: old_rank; new_rank **(in your case is "rank change: novice; Apprentice")**

```
ranks:
    Novice:
        requirements:
            time:
                value: 10h
        results:
            rank change: Novice; Apprentice
            command: 'say &p just got a promotion; broadcast &p has just been promoted to Apprentice!'
            command: 'adjustbonusclaimblocks &p 100'
            message: 'Congratulations, you are now an Apprentice!'
            message: 'You have been awarded 100 claim blocks for ranking up!'
            message: 'You can now set a total of 10 homes!'
    Apprentice:
        requirements:
            time:
                value: 20h
        results:
            rank change: Apprentice; Journeyman
            command: 'say &p just got a promotion; broadcast &p has just been promoted to Journeyman!'
            command: 'adjustbonusclaimblocks &p 200'
            message: 'Congratulations, you are now a Journeyman!'
            message: 'You have been awarded 200 claim blocks for ranking up!'
            message: 'You can now set a total of 15 homes!'

```
I put this on my server and works good, put the right rank change in all ranks, good luck
