### ISSUE TITLE
JS Requirements

### ISSUE THREAD

**Issue by CaszGamerMD** [Staartvin/Autorank-2#642]
one of the things i wanted to do was make it so cave/spiders counted as one. i just learned enough .JS so i can make a js script to do just that, would be nice if AR could allow JS to be a req:
```
var spiderCount = Number("%statz_mobs_killed_SPIDER%");
var spiderCaveCount = Number("%statz_mobs_killed_CAVE_SPIDER%");
var spiderTotalCount =  (spiderCount + spiderCaveCount);

function getSpiderProgress() {

return spiderTotalCount

};

getSpiderProgress();
```

then in AR it would be like:
```
  requirements:
    javascript: spider.js
      expression: ==
      value: 1000
```

then if between the 2 spider types if it totals 1000 req is met.

:D im proud i learned a thing . :D
