### ISSUE TITLE
Not doing its job

### ISSUE THREAD

**Issue by Anton-Sandin** [Staartvin/Autorank-2#708]
Hey! I've added these ranks:

```
New:
    requirements:
        time:
            value: 0
    results:
    command: 
            value: "manuadd &p New"
            message: 'Congratulations, you are a filthy rich bastard!'
    options:
    infinite pathing: true
    auto choose: true
    
Homeless:
    requirements:
        time:
            value: 179
    command: 
            value: "manuadd &p Homeless"
            message: 'Congratulations, you are a filthy filthy bastard!'
    options:
    infinite pathing: true
    auto choose: true
```

And when reaching the requirements the path just gets completed and the rank or message isn't sent out / given to the player? 

Also, the new path doesn't get auto chosen and not the Homeless either?

**Comment by Anton-Sandin** [comment]
@Staartvin Would love to get your help on this, not sure if it's my fault or errors in the plugin itself.

**Comment by Anton-Sandin** [comment]
What i want: 

1. When the player first joins he/she should be assigned to the rank "New".
2. When the player has been playing 179 minutes he/she should be assigned the new role "Homeless"

Whats happening: 
1. The player doesnt get the path automatically.
2. The player doesnt recieve a message OR a rank when the path is completed just says after some time "AntyZ does not have Homeless as an active path!".

**Comment by Staartvin** [comment]
What version of Autorank are you using. This seems like an ancient one! I can't really provide any support for very old version like this.

**Comment by Anton-Sandin** [comment]
I'm using Version 4.3.3.

**Comment by Anton-Sandin** [comment]
```
New:
    upon choosing:
        message: 
            value: "Debug x01"
    requirements:
        time:
            value: 0
    results:
    command: 
            value: "manuadd &p New"
            message: 'Congratulations, you are a filthy rich bastard!'
    options:
    infinite pathing: true
    auto choose: true
    
Homeless:
    upon choosing:
        message: 
            value: "Debug x02"
    requirements:
        time:
            value: 179
            message: 'Congratulations, you are a filthy filthy bastard!'
    results:
            command: 
             value: "manuadd &p Homeless"
             command: 
             value: "tell &p Congratulations, you are now &a[&eHomeless!&a]"
    options:
    infinite pathing: true
    auto choose: true
```
Remade the code a bit into this. 
Groupmanager commands doesnt seem to be sent away or the messages.
Though /tell &p does work oddly enough.

**Comment by Staartvin** [comment]
Your formatting doesn't look exactly right. Look at the examples on this [wiki ](https://github.com/Staartvin/Autorank-2/wiki/How-to-configure-the-Paths.yml-file%3F) page. See how the 'command' section is spaced with four spaces below the 'results' key. Moreover, the 'value' of 'command' should be spaced accordingly (4 spaces below command). In fact, every 'indentation' should use 4 spaces.

**Comment by Anton-Sandin** [comment]
> Your formatting doesn't look exactly right. Look at the examples on this [wiki ](https://github.com/Staartvin/Autorank-2/wiki/How-to-configure-the-Paths.yml-file%3F) page. See how the 'command' section is spaced with four spaces below the 'results' key. Moreover, the 'value' of 'command' should be spaced accordingly (4 spaces below command). In fact, every 'indentation' should use 4 spaces.

Yes that was correct, all my code is now correct i belive, the ranks & commands now work, though the auto choosing doesnt work?

```
New:
    requirements:
        time:
            value: 0
    results:
        message: 
            value: "&bCongratulations, you are now, &b[&aNew&b]"
        command: 
            value: "manuadd &p New"               
    options:
        auto choose: true

Homeless:
    requirements:
        time:
            value: 179
    results:
        message: 
            value: "&bCongratulations, you are now, &a[&eHomeless&a]"
        command: 
            value: "manuadd &p Homeless"               
    options:
        auto choose: true
```
