### ISSUE TITLE
Time is not logged on first join

### ISSUE THREAD

**Issue by James-Cotterill** [Staartvin/Autorank-2#764]
Hi,

Hope you are well?

We have an issue where a player data is not available when they first join.

If you do /ar check it says there is no player or path named 'name'

As soon as they leave and then rejoin it can then be tracked?

Is there any known error for this?

Plugins: .Autorank, BlockParticles, BloodEffects*, BuycraftX, ChatEx*, Citizens, ClearLag, ConsoleSpamFix, CoreProtect, CratesPlus, dtlTraders, Essentials, Essentials_WarpGUI, EssentialsSpawn, FireworkOnJoin*, HolographicDisplays, IridiumSkyblock, MessageAnnouncer, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, MyTrip, OreCrops, PermissionsEx*, PlaceholderAPI, PureTickets, sdm*, ServerListPlus*, SignEditor, Spawnx, Statz, TabList, Vault, Votifier, VotingPlugin, WorldEdit, WorldGuard, WorldGuardExtraFlags

```yaml
Paths:
Novice:
  prerequisites:
    in group:
      value: Beginner
  requirements:
    time:
      value: 2h
    money: 
      value: 50
    votes:
      value: 3
  results:
    money:
      value: 100
    command:
      value: pex user &p group set Novice
      #value: broadcast &p was promoted to Novice!
    message:
      value: &c&k*&e&lSparkie Skyblock&c&k* &8» &4&lCongratulations, you have been promoted to Novice!
Member:
  prerequisites:
    in group:
      value: Novice
  requirements:
    time:
      value: 6h
    money: 
      value: 100
    votes:
     value: 10
  results:
    money:
      value: 200
    command:
      value: pex user &p group set Member
      #value: broadcast &p was promoted to Member!
    message:
      value: &c&k*&e&lSparkie Skyblock&c&k* &8» &4&lCongratulations, you have been promoted to Member!
Advanced:
  prerequisites:
    in group:
      value: Member
  requirements:
    time:
      value: 12h
    money: 
      value: 150
    votes:
     value: 25
  results:
    money:
      value: 500
    command:
      value: pex user &p group set Advanced
      #value: broadcast &p was promoted to Advanced!
    message:
      value: &c&k*&e&lSparkie Skyblock&c&k* &8» &4&lCongratulations, you have been promoted to Advanced!
Veteran:
  prerequisites:
    in group:
      value: Veteran
  requirements:
    time:
      value: 24h
    money: 
      value: 200
    votes:
     value: 50
  results:
    money:
      value: 1000
    command:
      value: pex user &p group set Veteran
      #value: broadcast &p was promoted to Veteran!
    message:
      value: &c&k*&e&lSparkie Skyblock&c&k* &8» &4&lCongratulations, you have been promoted to Veteran!
```

Thank you
